<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ReportTemplate;

class ReportTemplatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $templates = [
            // Academic Reports
            [
                'name' => 'Student Masterlist',
                'slug' => 'student-masterlist',
                'description' => 'Complete roster of all students with filtering options by grade level, section, and status.',
                'category' => ReportTemplate::CATEGORY_ACADEMIC,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [
                    ['key' => 'lrn', 'label' => 'LRN', 'type' => 'text'],
                    ['key' => 'name', 'label' => 'Student Name', 'type' => 'text'],
                    ['key' => 'grade_level', 'label' => 'Grade Level', 'type' => 'text'],
                    ['key' => 'section', 'label' => 'Section', 'type' => 'text'],
                    ['key' => 'gender', 'label' => 'Gender', 'type' => 'text'],
                    ['key' => 'birthdate', 'label' => 'Birthdate', 'type' => 'date'],
                    ['key' => 'age', 'label' => 'Age', 'type' => 'number'],
                    ['key' => 'contact', 'label' => 'Contact', 'type' => 'text'],
                    ['key' => 'status', 'label' => 'Status', 'type' => 'badge'],
                ],
                'filters' => ['school_year_id', 'grade_level_id', 'section_id', 'gender', 'status'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01"/>',
                'color' => 'blue',
            ],
            [
                'name' => 'Grade Summary Report',
                'slug' => 'grade-summary',
                'description' => 'Comprehensive grade report showing quarterly grades and final averages by student and subject.',
                'category' => ReportTemplate::CATEGORY_ACADEMIC,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [
                    ['key' => 'student_name', 'label' => 'Student Name', 'type' => 'text'],
                    ['key' => 'subject', 'label' => 'Subject', 'type' => 'text'],
                    ['key' => 'section', 'label' => 'Section', 'type' => 'text'],
                    ['key' => 'q1', 'label' => 'Q1', 'type' => 'number'],
                    ['key' => 'q2', 'label' => 'Q2', 'type' => 'number'],
                    ['key' => 'q3', 'label' => 'Q3', 'type' => 'number'],
                    ['key' => 'q4', 'label' => 'Q4', 'type' => 'number'],
                    ['key' => 'final', 'label' => 'Final', 'type' => 'number'],
                    ['key' => 'remarks', 'label' => 'Remarks', 'type' => 'badge'],
                ],
                'filters' => ['school_year_id', 'section_id', 'subject_id'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/>',
                'color' => 'green',
            ],
            [
                'name' => 'Honor Roll',
                'slug' => 'honor-roll',
                'description' => 'List of students who achieved honors based on general average.',
                'category' => ReportTemplate::CATEGORY_ACADEMIC,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [
                    ['key' => 'rank', 'label' => 'Rank', 'type' => 'number'],
                    ['key' => 'student_name', 'label' => 'Student Name', 'type' => 'text'],
                    ['key' => 'section', 'label' => 'Section', 'type' => 'text'],
                    ['key' => 'general_average', 'label' => 'General Average', 'type' => 'number'],
                    ['key' => 'honor', 'label' => 'Honor', 'type' => 'badge'],
                ],
                'filters' => ['school_year_id', 'grade_level_id', 'min_average'],
                'default_params' => ['min_average' => 90],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"/>',
                'color' => 'purple',
            ],
            [
                'name' => 'Class Performance Report',
                'slug' => 'class-performance',
                'description' => 'Performance metrics for each section including average grades and passing rates.',
                'category' => ReportTemplate::CATEGORY_ACADEMIC,
                'type' => ReportTemplate::TYPE_COMBINED,
                'columns' => [
                    ['key' => 'section', 'label' => 'Section', 'type' => 'text'],
                    ['key' => 'grade_level', 'label' => 'Grade Level', 'type' => 'text'],
                    ['key' => 'adviser', 'label' => 'Adviser', 'type' => 'text'],
                    ['key' => 'total_students', 'label' => 'Students', 'type' => 'number'],
                    ['key' => 'average_grade', 'label' => 'Avg Grade', 'type' => 'number'],
                    ['key' => 'passing_rate', 'label' => 'Passing Rate', 'type' => 'percentage'],
                ],
                'filters' => ['school_year_id', 'section_id', 'grade_level_id'],
                'chart_config' => [
                    'type' => 'bar',
                    'x_axis' => 'section',
                    'y_axis' => 'average_grade',
                ],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/>',
                'color' => 'indigo',
            ],

            // Attendance Reports
            [
                'name' => 'Attendance Summary',
                'slug' => 'attendance-summary',
                'description' => 'Daily attendance records with present, absent, and late counts by student.',
                'category' => ReportTemplate::CATEGORY_ATTENDANCE,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [
                    ['key' => 'student_name', 'label' => 'Student Name', 'type' => 'text'],
                    ['key' => 'section', 'label' => 'Section', 'type' => 'text'],
                    ['key' => 'present', 'label' => 'Present', 'type' => 'number'],
                    ['key' => 'absent', 'label' => 'Absent', 'type' => 'number'],
                    ['key' => 'late', 'label' => 'Late', 'type' => 'number'],
                    ['key' => 'total', 'label' => 'Total', 'type' => 'number'],
                    ['key' => 'attendance_rate', 'label' => 'Rate', 'type' => 'percentage'],
                ],
                'filters' => ['section_id', 'start_date', 'end_date'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"/>',
                'color' => 'amber',
            ],
            [
                'name' => 'Attendance Trend',
                'slug' => 'attendance-trend',
                'description' => 'Visual trend of attendance rates over a specified time period.',
                'category' => ReportTemplate::CATEGORY_ATTENDANCE,
                'type' => ReportTemplate::TYPE_CHART,
                'columns' => [
                    ['key' => 'date', 'label' => 'Date', 'type' => 'date'],
                    ['key' => 'total', 'label' => 'Total', 'type' => 'number'],
                    ['key' => 'present', 'label' => 'Present', 'type' => 'number'],
                    ['key' => 'rate', 'label' => 'Rate', 'type' => 'percentage'],
                ],
                'filters' => ['section_id', 'days'],
                'default_params' => ['days' => 30],
                'chart_config' => [
                    'type' => 'line',
                    'x_axis' => 'date',
                    'y_axis' => 'rate',
                ],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z"/>',
                'color' => 'cyan',
            ],

            // Enrollment Reports
            [
                'name' => 'Enrollment Statistics',
                'slug' => 'enrollment-statistics',
                'description' => 'Enrollment numbers broken down by grade level and section.',
                'category' => ReportTemplate::CATEGORY_ENROLLMENT,
                'type' => ReportTemplate::TYPE_COMBINED,
                'columns' => [
                    ['key' => 'grade_level', 'label' => 'Grade Level', 'type' => 'text'],
                    ['key' => 'total', 'label' => 'Total', 'type' => 'number'],
                    ['key' => 'male', 'label' => 'Male', 'type' => 'number'],
                    ['key' => 'female', 'label' => 'Female', 'type' => 'number'],
                ],
                'filters' => ['school_year_id', 'grade_level_id'],
                'chart_config' => [
                    'type' => 'bar',
                    'x_axis' => 'grade_level',
                    'y_axis' => 'total',
                ],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"/>',
                'color' => 'teal',
            ],

            // Analytics Reports
            [
                'name' => 'At-Risk Students Report',
                'slug' => 'dropout-risk',
                'description' => 'Identify students at risk of dropping out based on attendance and grade patterns.',
                'category' => ReportTemplate::CATEGORY_ANALYTICS,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [
                    ['key' => 'student_name', 'label' => 'Student Name', 'type' => 'text'],
                    ['key' => 'section', 'label' => 'Section', 'type' => 'text'],
                    ['key' => 'attendance_rate', 'label' => 'Attendance', 'type' => 'percentage'],
                    ['key' => 'average_grade', 'label' => 'Avg Grade', 'type' => 'number'],
                    ['key' => 'risk_factors', 'label' => 'Risk Factors', 'type' => 'text'],
                    ['key' => 'risk_level', 'label' => 'Risk Level', 'type' => 'badge'],
                ],
                'filters' => ['school_year_id', 'attendance_threshold', 'grade_threshold'],
                'default_params' => [
                    'attendance_threshold' => 75,
                    'grade_threshold' => 75,
                ],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/>',
                'color' => 'red',
            ],
            [
                'name' => 'Teacher Workload Report',
                'slug' => 'teacher-workload',
                'description' => 'Overview of teaching assignments and student load per teacher.',
                'category' => ReportTemplate::CATEGORY_ANALYTICS,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [
                    ['key' => 'teacher_name', 'label' => 'Teacher Name', 'type' => 'text'],
                    ['key' => 'specialization', 'label' => 'Specialization', 'type' => 'text'],
                    ['key' => 'sections_handled', 'label' => 'Sections', 'type' => 'number'],
                    ['key' => 'subjects', 'label' => 'Subjects', 'type' => 'text'],
                    ['key' => 'total_students', 'label' => 'Total Students', 'type' => 'number'],
                ],
                'filters' => [],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/>',
                'color' => 'orange',
            ],

            // DepEd Compliance Reports
            [
                'name' => 'SF1 - School Register',
                'slug' => 'sf1-school-register',
                'description' => 'DepEd School Register form with complete student information.',
                'category' => ReportTemplate::CATEGORY_COMPLIANCE,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [
                    ['key' => 'no', 'label' => 'No.', 'type' => 'number'],
                    ['key' => 'lrn', 'label' => 'LRN', 'type' => 'text'],
                    ['key' => 'name', 'label' => 'Learner Name', 'type' => 'text'],
                    ['key' => 'gender', 'label' => 'Sex', 'type' => 'text'],
                    ['key' => 'birthdate', 'label' => 'Birth Date', 'type' => 'date'],
                    ['key' => 'age', 'label' => 'Age', 'type' => 'number'],
                    ['key' => 'mother_tongue', 'label' => 'Mother Tongue', 'type' => 'text'],
                    ['key' => 'religion', 'label' => 'Religion', 'type' => 'text'],
                    ['key' => 'address', 'label' => 'Address', 'type' => 'text'],
                    ['key' => 'father_name', 'label' => "Father's Name", 'type' => 'text'],
                    ['key' => 'mother_name', 'label' => "Mother's Name", 'type' => 'text'],
                    ['key' => 'guardian_name', 'label' => "Guardian's Name", 'type' => 'text'],
                    ['key' => 'guardian_contact', 'label' => 'Contact', 'type' => 'text'],
                ],
                'filters' => ['school_year_id', 'section_id'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>',
                'color' => 'gray',
            ],
            [
                'name' => 'SF2 - Daily Attendance',
                'slug' => 'sf2-daily-attendance',
                'description' => 'DepEd Daily Attendance Report of Learners.',
                'category' => ReportTemplate::CATEGORY_COMPLIANCE,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [
                    ['key' => 'no', 'label' => 'No.', 'type' => 'number'],
                    ['key' => 'name', 'label' => 'Name', 'type' => 'text'],
                    ['key' => 'days_present', 'label' => 'Days Present', 'type' => 'number'],
                    ['key' => 'days_absent', 'label' => 'Days Absent', 'type' => 'number'],
                    ['key' => 'days_late', 'label' => 'Days Late', 'type' => 'number'],
                    ['key' => 'total_days', 'label' => 'Total Days', 'type' => 'number'],
                ],
                'filters' => ['section_id', 'month', 'school_year_id'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/>',
                'color' => 'gray',
            ],
            [
                'name' => 'SF3 - Books Issued and Returned',
                'slug' => 'sf3-books',
                'description' => 'DepEd record of books issued and returned by students.',
                'category' => ReportTemplate::CATEGORY_COMPLIANCE,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [],
                'filters' => ['section_id'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"/>',
                'color' => 'gray',
            ],
            [
                'name' => 'SF4 - Monthly Learner Movement and Attendance',
                'slug' => 'sf4-monthly-movement',
                'description' => 'DepEd monthly movement and attendance summary.',
                'category' => ReportTemplate::CATEGORY_COMPLIANCE,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [],
                'filters' => ['section_id'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>',
                'color' => 'gray',
            ],
            [
                'name' => 'SF5 - Report on Promotion and Level of Proficiency',
                'slug' => 'sf5-promotion',
                'description' => 'DepEd report on promotion and proficiency levels by grade.',
                'category' => ReportTemplate::CATEGORY_COMPLIANCE,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [],
                'filters' => ['grade_level_id', 'school_year_id'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/>',
                'color' => 'gray',
            ],
            [
                'name' => 'SF6 - Summary Report on Promotion',
                'slug' => 'sf6-summary-promotion',
                'description' => 'DepEd summary report on promotion and retention.',
                'category' => ReportTemplate::CATEGORY_COMPLIANCE,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [],
                'filters' => ['grade_level_id', 'school_year_id'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>',
                'color' => 'gray',
            ],
            [
                'name' => 'SF7 - School Personnel Assignment List',
                'slug' => 'sf7-personnel',
                'description' => 'DepEd list of teaching and non-teaching personnel assignments.',
                'category' => ReportTemplate::CATEGORY_COMPLIANCE,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [],
                'filters' => ['school_year_id'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"/>',
                'color' => 'gray',
            ],
            [
                'name' => 'SF8 - Learner Health and Nutrition',
                'slug' => 'sf8-health-nutrition',
                'description' => 'DepEd report on learner health and nutrition profile.',
                'category' => ReportTemplate::CATEGORY_COMPLIANCE,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [],
                'filters' => ['section_id'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/>',
                'color' => 'gray',
            ],
            [
                'name' => 'SF9 - Report Card',
                'slug' => 'sf9-report-card',
                'description' => 'DepEd Learner Progress Report Card.',
                'category' => ReportTemplate::CATEGORY_COMPLIANCE,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [],
                'filters' => ['section_id', 'student_id'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>',
                'color' => 'gray',
            ],
            [
                'name' => 'SF10 - Learner Permanent Record',
                'slug' => 'sf10-permanent-record',
                'description' => 'DepEd Learner Permanent Academic Record.',
                'category' => ReportTemplate::CATEGORY_COMPLIANCE,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [],
                'filters' => ['student_id'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"/>',
                'color' => 'gray',
            ],
            [
                'name' => 'Kindergarten Assessment',
                'slug' => 'kindergarten-assessment',
                'description' => 'DepEd Kindergarten Developmental Domains Assessment.',
                'category' => ReportTemplate::CATEGORY_COMPLIANCE,
                'type' => ReportTemplate::TYPE_TABLE,
                'columns' => [],
                'filters' => ['section_id', 'student_id'],
                'icon' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>',
                'color' => 'gray',
            ],
        ];

        foreach ($templates as $template) {
            ReportTemplate::firstOrCreate(
                ['slug' => $template['slug']],
                array_merge($template, [
                    'is_system' => true,
                    'is_active' => true,
                ])
            );
        }

        $this->command->info('Report templates seeded successfully!');
    }
}
