<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Role;
use App\Models\Student;
use App\Models\Enrollment;
use App\Models\SchoolYear;
use App\Models\GradeLevel;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules\Password;
use Illuminate\View\View;
use Illuminate\Support\Facades\DB;
use App\Models\Setting;
use App\Services\SettingsEnforcer;


class RegisteredUserController extends Controller
{
    /**
     * Show registration form (OLD - redirects to landing with panel open)
     */
    public function create(): \Illuminate\Http\RedirectResponse
    {
        if (!SettingsEnforcer::isRegistrationEnabled()) {
            abort(403, 'User registration is currently disabled.');
        }

        // Redirect to landing page and flash panel mode so the auth panel opens once
        return redirect('/')->with('panel_mode', 'register');
    }

    /**
     * NEW: Show standalone registration page for new/transferee pupils
     */
    public function showRegistrationPage(): View
    {
        if (!SettingsEnforcer::isRegistrationEnabled()) {
            abort(403, 'User registration is currently disabled.');
        }

        $gradeLevels = GradeLevel::all();

        return view('auth.register-page', compact('gradeLevels'));
    }

    /**
     * Generate a unique LRN for new students in the format 120231######
     */
    private function generateNewStudentLrn(): string
    {
        $prefix = '120231';
        $lastStudent = Student::where('lrn', 'like', $prefix . '%')
            ->whereRaw('LENGTH(lrn) = 12')
            ->orderByDesc('lrn')
            ->first();

        if ($lastStudent) {
            $lastSuffix = (int) substr($lastStudent->lrn, 6);
            $newSuffix = $lastSuffix + 1;
        } else {
            $newSuffix = 1;
        }

        return $prefix . str_pad($newSuffix, 6, '0', STR_PAD_LEFT);
    }

        /**
     * Build full name from split name parts
     */
    private function buildFullName(?string $last, ?string $first, ?string $middle): ?string
    {
        $parts = array_filter([$first, $middle, $last]);
        return empty($parts) ? null : implode(' ', $parts);
    }


    /**
     * Handle registration
     */
    public function store(Request $request)
    {
        if (!SettingsEnforcer::isRegistrationEnabled()) {
            return redirect('/')->withErrors(['error' => 'User registration is currently disabled.'])->withInput()->with('panel_mode', 'register');
        }

        $studentType = $request->input('type', 'new');
        
        // Build full LRN based on student type
        if ($studentType === 'transferee') {
            // Transferee: must provide full 12-digit LRN from previous school
            $fullLrn = $request->input('lrn');
        } elseif ($studentType === 'continuing') {
            // Continuing: prefix + suffix
            if ($request->filled('lrn_suffix')) {
                $fullLrn = '120231' . $request->lrn_suffix;
            } else {
                $fullLrn = null;
            }
        } else {
            // New pupils: no LRN yet, will be generated by school after enrollment
            $fullLrn = null;
        }

        $validator = \Validator::make($request->all(), [
            'lrn' => [
                'nullable',
                function ($attribute, $value, $fail) use ($studentType) {
                    if ($studentType !== 'transferee') return;
                    if (empty($value)) {
                        $fail('The LRN is required for transferee students.');
                        return;
                    }
                    if (!preg_match('/^\d{12}$/', $value)) {
                        $fail('The LRN must be exactly 12 digits.');
                        return;
                    }
                    if (Student::where('lrn', $value)->exists()) {
                        $fail('The LRN is already taken.');
                    }
                },
            ],

            'first_name' => 'required|string|max:255',
            'middle_name' => 'nullable|string|max:255',
            'last_name' => 'required|string|max:255',
            'suffix' => 'nullable|string|max:10',

            'birthday' => 'required|date',
            'birth_place' => 'required|string|max:255',
            'gender' => 'required|in:Male,Female,Other',
            'nationality' => 'required|string|max:255',
            'religion' => 'required|string|max:255',

            // New DepEd fields
            'psa_birth_cert_no' => 'nullable|string|max:50',
            'is_ip' => 'nullable|boolean',
            'ip_specification' => 'nullable|string|max:100|required_if:is_ip,1',
            'is_4ps_beneficiary' => 'nullable|boolean',
            'household_id_4ps' => 'nullable|string|max:50|required_if:is_4ps_beneficiary,1',
            'is_returning_balik_aral' => 'nullable|boolean',
            'has_lrn' => 'nullable|boolean',

            // Parent/Guardian - new split name fields
            'father_last_name' => 'nullable|string|max:255',
            'father_first_name' => 'nullable|string|max:255',
            'father_middle_name' => 'nullable|string|max:255',
            'father_contact' => 'nullable|string|size:11|regex:/^\d{11}$/',
            'father_occupation' => 'nullable|string|max:255',

            'mother_last_name' => 'nullable|string|max:255',
            'mother_first_name' => 'nullable|string|max:255',
            'mother_middle_name' => 'nullable|string|max:255',
            'mother_contact' => 'nullable|string|size:11|regex:/^\d{11}$/',
            'mother_occupation' => 'nullable|string|max:255',

            'guardian_last_name' => 'nullable|string|max:255',
            'guardian_first_name' => 'nullable|string|max:255',
            'guardian_middle_name' => 'nullable|string|max:255',
            'guardian_name' => 'nullable|string|max:255',
            'guardian_relationship' => 'required|string|max:255',
            'guardian_contact' => 'nullable|string|size:11|regex:/^\d{11}$/',

            // Address
            'street_address' => 'required|string|max:255',
            'street_name' => 'nullable|string|max:255',
            'barangay' => 'required|string|max:255',
            'city' => 'required|string|max:255',
            'province' => 'required|string|max:255',
            'zip_code' => 'required|string|max:20',

            // Permanent address
            'same_as_current_address' => 'nullable|boolean',
            'permanent_street_address' => 'nullable|string|max:255|required_if:same_as_current_address,0',
            'permanent_barangay' => 'nullable|string|max:100|required_if:same_as_current_address,0',
            'permanent_city' => 'nullable|string|max:100|required_if:same_as_current_address,0',
            'permanent_province' => 'nullable|string|max:100|required_if:same_as_current_address,0',
            'permanent_zip_code' => 'nullable|string|max:20|required_if:same_as_current_address,0',

            // Academic
            'grade_level_id' => 'required|exists:grade_levels,id',
            'type' => 'required|in:new,transferee,continuing',

            // Returning/Transferee fields
            'last_grade_level_completed' => 'nullable|string|max:50',
            'last_school_year_completed' => 'nullable|string|max:20',
            'previous_school' => 'nullable|string|max:255|required_if:type,transferee',
            'previous_school_id' => 'nullable|string|max:20',

            // Account
            'username' => 'required|string|max:50|unique:users,username',
            'email' => 'required|email|max:255|unique:users,email',
            'password' => ['required', 'confirmed', SettingsEnforcer::getPasswordRules()],
            'photo' => 'nullable|image|max:2048',

            // Demographics
            'ethnicity' => 'required|string|max:100',
            'mother_tongue' => 'required|string|max:100',
            'remarks' => 'nullable|string|max:255',
            
                   // Documents - dynamic based on pupil type
            'birth_certificate' => 'nullable|file|mimes:pdf,jpg,jpeg,png|max:5120',
            'report_card' => 'nullable|file|mimes:pdf,jpg,jpeg,png|max:5120',
            'good_moral' => 'nullable|file|mimes:pdf,jpg,jpeg,png|max:5120',
            'transfer_credential' => 'nullable|file|mimes:pdf,jpg,jpeg,png|max:5120',
        ]);

                // Custom document validation based on pupil type
        $validator->after(function ($validator) use ($request, $studentType) {
            if ($studentType === 'new') {
                if (!$request->hasFile('birth_certificate')) {
                    $validator->errors()->add('birth_certificate', 'Birth Certificate is required for new pupils.');
                }
            } elseif ($studentType === 'transferee') {
                $requiredDocs = [
                    'birth_certificate' => 'Birth Certificate',
                    'report_card' => 'Report Card / Form 138',
                    'good_moral' => 'Certificate of Good Moral Character',
                    'transfer_credential' => 'Transfer Credentials / Honorable Dismissal',
                ];
                foreach ($requiredDocs as $field => $label) {
                    if (!$request->hasFile($field)) {
                        $validator->errors()->add($field, $label . ' is required for transferee pupils.');
                    }
                }
            }
            // Continuing pupils: all documents optional, no validation needed
        });


        if ($validator->fails()) {
            return redirect()->route('register.page')
                ->withErrors($validator)
                ->withInput();
        }

        $validated = $validator->validated();

        DB::beginTransaction();

        try {
            // Get role
            $studentRole = Role::where('name', 'pupil')->firstOrFail();

            // Handle photo
            $photoPath = $request->hasFile('photo')
                ? $request->file('photo')->store('photos', 'public')
                : null;

            // Create user
            $user = User::create([
                'first_name' => $request->first_name,
                'middle_name' => $request->middle_name,
                'last_name' => $request->last_name,
                'suffix' => $request->suffix,
                'birthday' => $request->birthday,
                'username' => $request->username,
                'email' => $request->email,
                'password' => Hash::make($request->password),
                'password_updated_at' => now(),
                'role_id' => $studentRole->id,
                'photo' => $photoPath,
                'is_active' => 0, // cannot login yet
            ]);

            // Build full names from split fields
            $fatherName = $this->buildFullName(
                $request->father_last_name,
                $request->father_first_name,
                $request->father_middle_name
            );
            $motherName = $this->buildFullName(
                $request->mother_last_name,
                $request->mother_first_name,
                $request->mother_middle_name
            );
            $guardianName = $request->guardian_name
                ?: $this->buildFullName(
                    $request->guardian_last_name,
                    $request->guardian_first_name,
                    $request->guardian_middle_name
                );

            // Handle permanent address
            $sameAsCurrent = $request->boolean('same_as_current_address', true);
            $permanentStreet = $sameAsCurrent ? $request->street_address : $request->permanent_street_address;
            $permanentStreetName = $sameAsCurrent ? $request->street_name : $request->permanent_street_name;
            $permanentBarangay = $sameAsCurrent ? $request->barangay : $request->permanent_barangay;
            $permanentCity = $sameAsCurrent ? $request->city : $request->permanent_city;
            $permanentProvince = $sameAsCurrent ? $request->province : $request->permanent_province;
            $permanentZip = $sameAsCurrent ? $request->zip_code : $request->permanent_zip_code;

            // Create student (pending)
            $student = $user->student()->create([
                'lrn' => $fullLrn,
                'first_name'  => $request->first_name,
                'middle_name' => $request->middle_name,
                'last_name'   => $request->last_name,
                'suffix' => $request->suffix,
                'has_lrn' => $request->boolean('has_lrn', false),
                'birthdate' => $request->birthday,
                'birth_place' => $request->birth_place,
                'psa_birth_cert_no' => $request->psa_birth_cert_no,
                'gender' => $request->gender,
                'nationality' => $request->nationality,
                'religion' => $request->religion,

                // New DepEd fields
                'is_ip' => $request->boolean('is_ip', false),
                'ip_specification' => $request->ip_specification,
                'is_4ps_beneficiary' => $request->boolean('is_4ps_beneficiary', false),
                'household_id_4ps' => $request->household_id_4ps,
                'is_returning_balik_aral' => $request->boolean('is_returning_balik_aral', false),

                // Parents
                'father_name' => $fatherName,
                'father_occupation' => $request->father_occupation,
                'father_contact' => $request->father_contact,
                'mother_name' => $motherName,
                'mother_occupation' => $request->mother_occupation,
                'mother_contact' => $request->mother_contact,

                // Guardian
                'guardian_name' => $guardianName,
                'guardian_relationship' => $request->guardian_relationship,
                'guardian_contact' => $request->guardian_contact,

                // Current Address
                'street_address' => $request->street_address,
                'barangay' => $request->barangay,
                'city' => $request->city,
                'province' => $request->province,
                'zip_code' => $request->zip_code,

                // Permanent Address
                'same_as_current_address' => $sameAsCurrent,
                'permanent_street_address' => $permanentStreet,
                'permanent_street_name' => $permanentStreetName,
                'permanent_barangay' => $permanentBarangay,
                'permanent_city' => $permanentCity,
                'permanent_province' => $permanentProvince,
                'permanent_zip_code' => $permanentZip,

                'status' => 'inactive',
                'grade_level_id' => $request->grade_level_id,
                'section_id' => null,

                'ethnicity' => $request->ethnicity,
                'mother_tongue' => $request->mother_tongue,
                'remarks' => $request->remarks,
                
                // Returning/Transferee
                'last_grade_level_completed' => $request->last_grade_level_completed,
                'last_school_year_completed' => $request->last_school_year_completed,
                'previous_school' => $request->previous_school,
                'previous_school_id' => $request->previous_school_id,

                // Document paths will be updated after upload
                'birth_certificate_path' => null,
                'report_card_path' => null,
                'good_moral_path' => null,
                'transfer_credential_path' => null,
                'registration_status' => 'pending',
            ]);
            
            // Handle document uploads
            $documentPaths = [];
            
            if ($request->hasFile('birth_certificate')) {
                $documentPaths['birth_certificate_path'] = $request->file('birth_certificate')->store('student-documents/' . $student->id, 'public');
            }
            
            if ($request->hasFile('report_card')) {
                $documentPaths['report_card_path'] = $request->file('report_card')->store('student-documents/' . $student->id, 'public');
            }
            
            if ($request->hasFile('good_moral')) {
                $documentPaths['good_moral_path'] = $request->file('good_moral')->store('student-documents/' . $student->id, 'public');
            }
            
            if ($request->hasFile('transfer_credential')) {
                $documentPaths['transfer_credential_path'] = $request->file('transfer_credential')->store('student-documents/' . $student->id, 'public');
            }
            
            // Update student with document paths
            if (!empty($documentPaths)) {
                $student->update($documentPaths);
            }

            // ✅ Get ACTIVE school year
            $currentYear = SchoolYear::where('is_active', 1)->first();

            if (!$currentYear) {
                throw new \Exception('No active school year found.');
            }

            // ✅ Prevent duplicate enrollment
            $existingEnrollment = Enrollment::where('student_id', $student->id)
                ->where('school_year_id', $currentYear->id)
                ->first();

            if (!$existingEnrollment) {
                Enrollment::create([
                    'student_id' => $student->id,
                    'school_year_id' => $currentYear->id,
                    'grade_level_id' => $request->grade_level_id,
                    'section_id' => null,

                    'type' => $request->type,
                    'status' => 'pending',

                                     'previous_school' => in_array($request->type, ['transferee', 'continuing'])
                        ? $request->previous_school
                        : null,
                    'previous_school_id' => $request->previous_school_id,

                    'enrollment_date' => now(),


                     // Store current school info at time of enrollment
    'school_name' => Setting::get('school_name'),
    'school_id' => Setting::get('deped_school_id'),
    'school_district' => Setting::get('school_district'),
    'school_division' => Setting::get('school_division'),
    'school_region' => Setting::get('school_region'),
                ]);
            }

            DB::commit();

            event(new Registered($user));

            return redirect()->route('login')
                ->with('success', 'Registration successful! Waiting for admin approval.');

        } catch (\Exception $e) {
            DB::rollBack();

            return redirect()->route('register.page')->withErrors([
                'error' => $e->getMessage()
            ])->withInput();
        }
    }

}